version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - JAVA_HOME=/opt/java/openjdk
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev  # Ajuste conforme o perfil desejado
      JAVA_HOME: /opt/java/openjdk
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: carro_atendimento
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqq
    ports:
      - "5672:5672"  # Porta padrão para conexões
      - "15672:15672"  # Porta para o painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
networks:
  app-network:
    driver: bridge
